spring.application.name=userapi
server.port=8080

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/banking_middleware
spring.datasource.username=user
spring.datasource.password=password123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable H2 (Optional)
spring.h2.console.enabled=false


